// Code generated by hertz generator.

package main

import (
	"github.com/Zarxdy34/alicloud_minecraft_server_manager/src/view"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", view.Ping)

	r.GET("/api/minecraft/server", view.MinecraftServerManage)

	// your code ...
}
