name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          
      - name: Build and release
      - uses: wangyoucao577/go-release-action@v1.32
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          goos: linux
          goarch: amd64
          release_tag: main
