name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          architecture: x64
      
      - name: Build
        run: |
          mkdir output
          go build -o output/alicloud_minecraft_server_manager

          
      - uses: actions/upload-artifact@v3
        with:
          name: alicloud_minecraft_server_manager
          path: output/alicloud_minecraft_server_manager
