name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo secret is ${{ secrets.ACTION_TOKEN }}
    - uses: wangyoucao577/go-release-action@v1.32
      with:
        github_token: ${{ secrets.ACTION_TOKEN }}
        goos: linux
        goarch: amd64
        goversion: 1.18
